[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my_package"
requires-python = ">=3.7"
dynamic = ["version"]

[project.optional-dependencies]
test = [
  "pytest >= 6.0.0",
  "uncertainties >= 3.1.7"
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
